fund_name: Motilal Oswal Midcap Fund Direct Growth
as_of: 2026-09-21 14:22 UTC
holdings_count: 30
total_weight: 95.02
holdings:
- symbol: PAYTM
  name: One97 Communications Ltd
  weight: 7.52
- symbol: KALYANKJIL
  name: Kalyan Jewellers India Ltd
  weight: 6.74
- symbol: ETERNAL
  name: Eternal Ltd
  weight: 5.35
- symbol: COFORGE
  name: Coforge Ltd
  weight: 4.8
- symbol: '517569'
  name: KEI Industries Ltd
  weight: 4.28
- symbol: ABCAPITAL
  name: Aditya Birla Capital Ltd
  weight: 4.04
- symbol: POLYCAB
  name: Polycab India Ltd
  weight: 3.73
- symbol: PERSISTENT
  name: Persistent Systems Ltd
  weight: 3.66
- symbol: TRENT
  name: Trent Ltd
  weight: 3.52
- symbol: SUPREMEIND
  name: Supreme Industries Ltd
  weight: 3.4
- symbol: FEDERALBNK
  name: The Federal Bank Ltd
  weight: 3.19
- symbol: ASTRAL
  name: Astral Ltd
  weight: 3.11
- symbol: SHRIRAMFIN
  name: Shriram Finance Ltd
  weight: 3.03
- symbol: VOLTAS
  name: Voltas Ltd
  weight: 2.86
- symbol: DIXON
  name: Dixon Technologies (India) Ltd
  weight: 2.85
- symbol: GROWW
  name: Billionbrains Garage Ventures Ltd
  weight: 2.84
- symbol: APLAPOLLO
  name: APL Apollo Tubes Ltd
  weight: 2.74
- symbol: SUNDRMFAST
  name: Sundram Fasteners Ltd
  weight: 2.61
- symbol: MAXHEALTH
  name: Max Healthcare Institute Ltd
  weight: 2.53
- symbol: BALKRISIND
  name: Balkrishna Industries Ltd
  weight: 2.45
- symbol: BHARTIARTL
  name: Bharti Airtel Ltd
  weight: 2.32
- symbol: BEL
  name: Bharat Electronics Ltd
  weight: 2.24
- symbol: CGPOWER
  name: CG Power and Industrial Solutions Ltd
  weight: 2.2
- symbol: IDFCFIRSTB
  name: IDFC First Bank Ltd
  weight: 2.11
- symbol: LUPIN
  name: Lupin Ltd
  weight: 2.03
- symbol: AUROPHARMA
  name: Aurobindo Pharma Ltd
  weight: 1.95
- symbol: COROMANDEL
  name: Coromandel International Ltd
  weight: 1.82
- symbol: DALBHARAT
  name: Dalmia Bharat Ltd
  weight: 1.74
- symbol: PRESTIGE
  name: Prestige Estates Projects Ltd
  weight: 1.7
- symbol: OBEROIRLTY
  name: Oberoi Realty Ltd
  weight: 1.66
